### PR TITLE
CW is positive, CCW is negative, according to the builtin turtle module.

### PR DESCRIPTION
**Pull request by rahularya50**
Python uses the `standard` turtle mode by default, not the `logo` mode, which is what this library uses internally.

Standard has zero at 3 o'clock and is positive in the CW direction, whereas logo has zero at 12 o'clock and positive in the CCW direction.

### CODE REVIEW

**Comment by kavigupta** [comment]
image
wait what?

**Comment by kavigupta** [comment]
is this some global setting I set at some point?

**Comment by kavigupta** [comment]
image
on my entirely unconfigured server

**Comment by rahularya50** [comment]
OK no, I see the problem. The module's behavior is fine. I was testing using the scheme turtle primitives. And the scheme interpreter sets `turtle.mode('logo')` when initialized.

**Comment by rahularya50** [comment]
```python
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import turtle
>>> turtle.mode("logo")
>>> turtle.setheading(0)
>>> turtle.right(90)
>>> turtle.heading()
90.0
>>> 
```

**Pull request merged**
